### ISSUE TITLE
Travis build fails on ghc 7.8

### ISSUE THREAD

**Issue by nh2** [nh2/call-haskell-from-anything#4]
I just restarted [this build](https://travis-ci.org/nh2/call-haskell-from-anything/builds/45870837), which was green before, and now it fails on GHC 7.8 while exactly the same code worked perfectly just a few days ealier:

```
The command "cabal build" exited with 0.
$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    lib = cdll.LoadLibrary("dist/build/call-haskell-from-anything.so/call-haskell-from-anything.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libHScall-haskell-from-anything-0.1.0.1-ghc7.8.3.so: cannot open shared object file: No such file or directory
```

No clue yet what's going on.

**Comment by nh2** [comment]
Ah, now I _do_ have an idea. Before it was installing Cabal 1.20, now it is installing Cabal 1.22.

Probably that's the difference!

**Comment by nh2** [comment]
Filed in cabal: https://github.com/haskell/cabal/issues/2330

**Comment by nh2** [comment]
Temporarily worked around it by restricting Travis to Cabal < 1.22.

**Comment by JoshCheek** [comment]
I can't get it to install the dependencies, I assume it's the same issue. 

```
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1
```

```
$ cabal install --only-dependencies --enable-shared -j8 --max-backjumps=-1
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: call-haskell-from-anything-0.1.0.2 (user goal)
trying: attoparsec-0.13.0.1 (dependency of call-haskell-from-anything-0.1.0.2)
trying: text-1.2.1.3 (dependency of attoparsec-0.13.0.1)
trying: binary-0.7.3.0/installed-a62... (dependency of text-1.2.1.3)
next goal: msgpack (dependency of call-haskell-from-anything-0.1.0.2)
rejecting: msgpack-1.0.0 (conflict: call-haskell-from-anything =>
msgpack>=0.7.1.5 && <1.0.0)
rejecting: msgpack-0.7.2.5 (conflict: text==1.2.1.3, msgpack => text==0.11.*)
rejecting: msgpack-0.7.1.5 (conflict: binary =>
bytestring==0.10.6.0/installed-3ca..., msgpack => bytestring==0.9.*)
rejecting: msgpack-0.7.1.4, 0.7.1.3, 0.7.1.2, 0.7.1.1, 0.7.1, 0.7.0, 0.6.4,
0.6.3, 0.6.2, 0.6.1.3, 0.6.1.2, 0.6.1.1, 0.6.1, 0.6.0.1, 0.6.0.0, 0.5.0.0,
0.4.0.1, 0.4.0, 0.3.1.1, 0.3.1, 0.3.0, 0.2.2, 0.2.0, 0.1.0 (conflict:
call-haskell-from-anything => msgpack>=0.7.1.5 && <1.0.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

I also tried installing text independently, to an earlier version, but it didn't work :(

```
$ cabal install 'text < 0.12.0' --max-backjumps=-1
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: text (user goal)
rejecting: text-1.2.1.3, 1.2.1.2, 1.2.1.1, 1.2.1.0, 1.2.0.6, 1.2.0.5, 1.2.0.4,
1.2.0.3, 1.2.0.2, 1.2.0.0, 1.1.1.4, 1.1.1.3, 1.1.1.2, 1.1.1.1, 1.1.1.0,
1.1.0.1, 1.1.0.0, 1.0.0.1, 1.0.0.0 (global constraint requires <0.12.0)
trying: text-0.11.3.1
trying: base-4.8.0.0/installed-901... (dependency of text-0.11.3.1)
next goal: deepseq (dependency of text-0.11.3.1)
rejecting: deepseq-1.4.1.1/installed-936..., 1.4.1.1, 1.4.1.0, 1.4.0.0
(conflict: text => deepseq>=1.1.0.0 && <1.4)
rejecting: deepseq-1.3.0.2 (conflict: base==4.8.0.0/installed-901..., deepseq
=> base>=4.3 && <4.8)
trying: deepseq-1.3.0.1
next goal: array (dependency of text-0.11.3.1)
rejecting: array-0.5.1.0/installed-e29..., 0.5.1.0, 0.5.0.0 (conflict: deepseq
=> array>=0.1 && <0.5)
rejecting: array-0.4.0.1 (conflict: base==4.8.0.0/installed-901..., array =>
base>=4.2 && <4.7)
rejecting: array-0.4.0.0 (conflict: base==4.8.0.0/installed-901..., array =>
base>=4.2 && <4.6)
rejecting: array-0.3.0.3 (conflict: base==4.8.0.0/installed-901..., array =>
base>=4.2 && <4.5)
rejecting: array-0.3.0.2, 0.3.0.1 (conflict: base==4.8.0.0/installed-901...,
array => base>=4.2 && <4.4)
rejecting: array-0.3.0.0 (conflict: base==4.8.0.0/installed-901..., array =>
base>=3 && <4.4)
rejecting: array-0.2.0.0, 0.1.0.0 (conflict: base==4.8.0.0/installed-901...,
array => base<4.3)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

I don't actually code in Haskell, so it's possible that I'm just ignorant about some obvious thing. Just thought the lib sounded cool and wanted to see if I could get the example to work, maybe see if there's some expensive / volatile bit of Ruby code I could push over to it. _shrug_

**Comment by nh2** [comment]
Ah it's kind of messy with Travis. Still no GHC 7.10 support even after 9 months of asking :(

**Comment by mvoidex** [comment]
@nh2, there is a way  to build with ghc-7.10 on travis, here's example [.travis.yml](https://github.com/mvoidex/hsdev/blob/master/.travis.yml)
